# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="mateusg"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias be="bundle exec"
alias bu="bundle update"
alias sublime="nocorrect subl"
alias "git lg"="nocorrect git lg"
alias lg="nocorrect git lg"
alias kicker_rails='kicker -r rails -b "spin push"'
alias etest="RAILS_ENV=test"
alias dumpdiff='git diff master > `date +"%Y-%m-%d---%H-%M-%S"`-`git rev-parse --abbrev-ref HEAD`.diff'

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse bundler)
plugins=(git brew cap gem osx terminalapp)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin":$PATH

# rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# RVM
if [ -s "$HOME/.rvm/scripts/rvm" ]; then
  source "$HOME/.rvm/scripts/rvm"
  PATH=$PATH:$HOME/.rvm/bin
fi

# Editor
export EDITOR="subl -n -w"

# Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"

# Go
export GOPATH=$HOME/Code/go
export PATH=$PATH:$GOPATH/bin

CXX="clang++-3.5 -stdlib=libc++"
CXXFLAGS="$CXXFLAGS -nostdinc++ -I/usr/local/opt/llvm35/lib/llvm-3.5/include/c++/v1"
LDFLAGS="$LDFLAGS -L/usr/local/opt/llvm35/lib/llvm-3.5/lib"

# added by travis gem
[ -f /Users/mateus/.travis/travis.sh ] && source /Users/mateus/.travis/travis.sh

# Qt5 
#export PATH="/usr/local/opt/qt5/bin:$PATH"
#export LDFLAGS="-L/usr/local/opt/qt5/lib:$LDFLAGS"
#export CPPFLAGS="-I/usr/local/opt/qt5/include:$CPPFLAGS"
#export PKG_CONFIG_PATH="/usr/local/opt/qt5/lib/pkgconfig:$PKG_CONFIG_PATH"

